vehicle = input("What is your vehicle?")
if vehicle == "Car":
    brand = input("What brand is your car?")
    if brand == "Audi":
        ...
    elif brand == "Toyota":
        ...
    elif brand == "Nissan":
        ...
    else:
        ...
elif vehicle == "Motorcycle":
    brand = input("What brand is your motorcycle?")
    if brand == "Yamaha":
        ...
    else:
        ...
else:
    print("I don't know what kind of vehicle is that")